name: Ping API every 2 minutes

on:
  schedule:
    - cron: '*/6 * * * *'

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl API
        run: curl -s https://portfolio-backend-i96y.onrender.com/api/test123
